// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNxitVMZlDHW55gqnOL5qjE87zchXCq4',
    appId: '1:196685869266:web:f8462b97ef99bfec857d0b',
    messagingSenderId: '196685869266',
    projectId: 'taskmanagement-c0fe6',
    authDomain: 'taskmanagement-c0fe6.firebaseapp.com',
    storageBucket: 'taskmanagement-c0fe6.firebasestorage.app',
    measurementId: 'G-6E4HEGKF4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdmasGFwQYy8__qjzsATtUcPNK-0q67w',
    appId: '1:196685869266:android:98af17151f638bb6857d0b',
    messagingSenderId: '196685869266',
    projectId: 'taskmanagement-c0fe6',
    storageBucket: 'taskmanagement-c0fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkBJXBstE7W8zjpKhQPuAVeeZrRKcjF_o',
    appId: '1:196685869266:ios:d8e32f37177cc48b857d0b',
    messagingSenderId: '196685869266',
    projectId: 'taskmanagement-c0fe6',
    storageBucket: 'taskmanagement-c0fe6.firebasestorage.app',
    iosBundleId: 'com.example.newTaskmanager2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkBJXBstE7W8zjpKhQPuAVeeZrRKcjF_o',
    appId: '1:196685869266:ios:d8e32f37177cc48b857d0b',
    messagingSenderId: '196685869266',
    projectId: 'taskmanagement-c0fe6',
    storageBucket: 'taskmanagement-c0fe6.firebasestorage.app',
    iosBundleId: 'com.example.newTaskmanager2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNxitVMZlDHW55gqnOL5qjE87zchXCq4',
    appId: '1:196685869266:web:ad5df86099ea4950857d0b',
    messagingSenderId: '196685869266',
    projectId: 'taskmanagement-c0fe6',
    authDomain: 'taskmanagement-c0fe6.firebaseapp.com',
    storageBucket: 'taskmanagement-c0fe6.firebasestorage.app',
    measurementId: 'G-X682LLQGSX',
  );
}
